[project]
name = "tdd-string-cal"
version = "0.1.0"
description = "A string calculator implementation using Test-Driven Development (TDD) approach."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.4",
]
